cats99/config/routes.rb
Cats99::Application.routes.draw do
  resources :cats
  resources :rental_requests
end

cats99/app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :name, :age, :birth_date, :color_id, :location_id, :sex

  belongs_to :location
  belongs_to :color #REV: you may consider just inferring age from birth date. 
  has_many :rental_requests
end

cats99/app/models/color.rb
class Color < ActiveRecord::Base #REV: nice normalization
  attr_accessible :color
  has_many :cats
end

cats99/app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name #REV: again, nice normalization.
  has_many :cats
end

cats99/app/models/rental_request.rb
class RentalRequest < ActiveRecord::Base
  attr_accessible :end_time, :start_time, :status, :cat_id

  belongs_to :cat
  validate :rental_period_does_not_overlap

  private
  def rental_period_does_not_overlap
    overlaps = RentalRequest.where("cat_id = ? AND
                        status = 1 AND
                        ((start_time BETWEEN ? AND ? ) OR #REV: for less comparisons, you could also say something like
                        (end_time BETWEEN ? AND ?))",#REV: !(start_time < self.end_time or end_time > self.start_time)
                          self.cat_id,
                          self.start_time,
                          self.end_time,
                          self.start_time,
                          self.end_time)
    unless overlaps.empty?
      errors[:cat_id] << "This cat is already rented for this time period."
    end
  end
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def new
    @cat = Cat.new
  end

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.includes(:color, :location).find(params[:id])
  end

  def create
    @cat = Cat.create!(params[:cat])
    #@cat.color_id = Color.find_or_create_by_name(params[:cat][:color_id]).id
    redirect_to cat_path(@cat)
  end

end

cats99/app/controllers/rental_requests_controller.rb
class RentalRequestsController < ApplicationController
	# REV Seems right to me!
  def index
    @rental_requests = RentalRequest.includes(:cats)
  end

  def show
    @rental_requests = RentalRequest.find(params[:id])
  end

  def create
    RentalRequest.create!(params[:rental_request])
  end

end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cats_helper.rb
module CatsHelper
end

cats99/app/helpers/rental_requests_helper.rb
module RentalRequestsHelper
end

cats99/app/views/cats/index.html.erb
<h1>LIST OF CATS</h1>
<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_path(cat) %></li>
  <% end %>
</ul>

<p><%= link_to "Add Cat", new_cat_path %></p>

cats99/app/views/cats/new.html.erb
<h1>Add a Cat</h1>
<form action="/cats" method="post">
  <label for="name">Name:</label>
  <input name = "cat[name]" id = "name" type = "text"><br />

  <input name = "cat[sex]" id="male" type = "radio" value = "0">
  <label for="male">Male</label><br />
  <input name = "cat[sex]" id="female" type = "radio" value = "1">
  <label for="female">Female</label><br />

  <label for="location">Location:</label>
  <input name = "location" id = "location" type = "text"><br />

  <label for="color">Color:</label>
  <input name = "color" id = "color" type = "text"><br />


  <input type="submit" value="Create Cat">

</form>

cats99/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<p>Age: <%= @cat.age %><br/>
Birth Date: <%= @cat.birth_date %><br/>
Color: <%= @cat.color.color %><br/>
Location: <%= @cat.location.name %><br/>
  Gender:
  <% if @cat.sex == 0 %>
    <%= "Male" %>
  <% else %>
    <%= "Female" %>
  <% end %>
</p>
<form action="/rental_request" method="post">
  <label for "cat_id">Cat ID #:</label>
  <input name = "rental_request[cat_id]" id = "cat_id" type = "number"><br />

  <label for "start_date">Start Date:</label>
  <input name = "rental_request[start_date]" id = "start_date" type = "text"><br/>
  <label for "end_date">End Date:</label>
  <input name = "rental_request[end_date]" id = "end_date" type = "text"><br/>
  <input type = "submit" value = "Submit Rental Request">
</form>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

cats99/app/views/rental_requests/_form.html.erb
<form action="/rental_request" method="post">
  <label for "cat_id">Cat ID #:</label>
  <input name = "rental_request[cat_id]" id = "cat_id" type = "number"><br />

  <label for "start_date">Start Date:</label>
  <input name = "rental_request[start_date]" id = "start_date" type = "text"><br/>
  <label for "end_date">End Date:</label>
  <input name = "rental_request[end_date]" id = "end_date" type = "text"><br/>
  <input type = "submit" value = "Submit Rental Request">
</form>

cats99/app/views/rental_requests/index.html.erb
<h1>LIST OF RENTAL REQUESTS</h1>
<ul>
  <% @rental_requests.each do |request| %>
    <li><%= link_to cat.name, cat_path(cat) %></li>
  <% end %>
</ul>